services:
  - type: web
    name: visionflow-backend
    env: python
    plan: free
    rootDir: /
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: GOOGLE_AI_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
